### ISSUE TITLE
README consistency?

### ISSUE THREAD

**Issue by sporeball** [hackclub/dinosaurs#267]
the titles of each dinosaur in the README have become more and more inconsistent with time:
- some titles include their author as part of a plain English string (e.g. `Upside-Down Orpheus by Ali A. Saleh 🙃`)
- some titles include their author as part of a snake_case string (e.g. `sporeball_catpheus`)
- and some titles don't mention their author at all (e.g. `a dinosaur trying, but failing to get money`)

additionally, some titles include `.png` at the end of their names (e.g. `roydeva026-dinohacker.png`), while others don't; and at least one title is misplaced relative to its dinosaur, as is the case with `MihirK018-mkdino.png`.

it might look nicer if each dinosaur's title were converted to plain English, like:
- `"Upside-Down Orpheus", by Ali A. Saleh`
- `"catpheus", by sporeball`
- `"dino hacker", by roydeva026`

for most of the dinosaurs in the README, a passable title should be able to be inferred by looking at its current title, and, if necessary, the PR that originally added it.

i'd be happy to take this on if this is something that others feel would be good to change, but i don't mind if this issue gets labeled `wontfix`, either.

**Comment by maxwofford** [comment]
(I'd guess) a bunch of these are coming from hack.af/draw-dino. If you want new PRs to be formatted a certain way I bet you can change the instructions there to make it happen.

**Comment by sporeball** [comment]
this is true, although me editing the instructions to suggest another format would realistically just create another format to clash with those being used already...
if for the sake of transparency and historical accuracy we'd like to avoid changing existing titles, that's completely fair, and i'll close.

**Comment by mikaeru** [comment]
so @sporeball can I change or reformat the dino picture's title i uploaded here?

**Comment by sporeball** [comment]
it's okay; it's probably better not to worry about it too much. closing.
