### ISSUE TITLE
Delete Wrong Branch

### ISSUE THREAD

**Issue by SmokinSpectre** [hackclub/dinosaurs#352]
Hey,
I made a wrong branch a while ago while making a pull request, It's called [HappyRex](https://github.com/hackclub/dinosaurs/tree/HappyRex) Could you delete it? I've already made the PR from a new branch.

**Comment by eilla1** [comment]
sure thing, i just deleted the `HappyRex` branch

**Comment by SmokinSpectre** [comment]
> sure thing, i just deleted the `HappyRex` branch. congrats on making your first PR!

Thanks! 🙂
