### ISSUE TITLE
GIFs

### ISSUE THREAD

**Issue by zachlatta** [hackclub/dinosaurs#4]
![](https://upload.wikimedia.org/wikipedia/commons/4/4a/Defcon_1_Type1.gif)

_**Warning:** Nuclear war is imminent._

---

While reviewing our mission-critical logistics, I chanced upon a breach in our system. We are missing Prophet Orpheus GIFs.

I've already pinged the DOD. Sergeant @MaxWofford, can you get on this right away?

**Comment by MaxWofford** [comment]
OMGWTFBBQ YES

**Comment by zachlatta** [comment]
Sir, has any progress been made on this front?

**Comment by zachlatta** [comment]
Closing for the time being to make sure that open issues are all things that we're actually planning on doing.

**Comment by paked** [comment]
Honestly sir, it's a shame this wasn't closed in military speak. Sir.
