### ISSUE TITLE
drawing site is dead!!

### ISSUE THREAD

**Issue by Terrorboy** [hackclub/dinosaurs#460]
https://hack.af/draw-dino

**Comment by cjdenio** [comment]
It should be back up! If you run into any more issues, you can visit https://draw-dino.hackclub.com directly.

**Comment by httpanand** [comment]
@cjdenio 
![image](https://user-images.githubusercontent.com/87514488/153129390-660e0ee1-3c53-4512-846a-610d3aa6992e.png)

**Comment by cjdenio** [comment]
Eek, looks like https://hack.af is having some trouble. 😱

https://draw-dino.hackclub.com works though!

**Comment by httpanand** [comment]
@cjdenio Its cleared ig
