### ISSUE TITLE
Move dino images to another directory for clean and convenient repo 

### ISSUE THREAD

**Issue by Muhammad-Ahsan-Rasheed** [hackclub/dinosaurs#639]
First of all huge applause for all contributors that we've more than 2000 images so it'll be great if we move all images to separate directory because readme file is way down to bottom. 

I'm thinking about creating a directory dinaosaur/images etc.

**Comment by exu3** [comment]
I like this idea. However, I think it would break community projects that depend on hackclub/dinosaurs; one that comes to mind is https://github.com/YodaLightsabr/get-a-dino/
