### ISSUE TITLE
ship-it

### ISSUE THREAD

**Issue by gemmabusoni** [hackclub/dinosaurs#7]
it's come to my attention that a ship-it project orpheus is not yet in existence. we have had to resort to using  meager images such as [THIS](http://i.imgur.com/7YFBefD.png). therefore, it must be made. i propose a collaboration between myself and @MaxWofford.

**Comment by zachlatta** [comment]
I move for making the collaboration between @gemmabusoni and @MaxWofford a
thing.

On Thu, Sep 17, 2015 at 12:53 AM, Gemma Busoni <notifications@github.com>
wrote:

> it's come to my attention that a ship-it project orpheus is not yet in
> existence. we have had to resort to using meager images such as THIS
> <http://i.imgur.com/7YFBefD.png>. therefore, it must be made. i propose a
> collaboration between myself and @MaxWofford
> <https://github.com/MaxWofford>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/dinosaurs/issues/7>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
I think this issue is a classic case of tragedy of the commons, where we've each individually prioritized other tasks without realizing we were undermining the goals of the organization as a whole by not completing this issue.

I move to prioritize this issue.

**Comment by zachlatta** [comment]
Unfortunately closing due to lack of time.
