### ISSUE TITLE
Move images to a folder

### ISSUE THREAD

**Issue by dishb** [hackclub/dinosaurs#818]
This way users aren't scrolling on the main page for centuries.

Moving the images to a folder would mean they click on the folder to view them, rather than be bombarded with a massive scroll-bar...

**Comment by dishb** [comment]
@ajs256 - Would it not be possible to configure the API so that it pulls images from a specific folder in the repository, rather than the root directory of the repository...?

**Comment by BrightTheBackpack** [comment]
Should be possible. Looking at the api, on line 6 of dino-png.js, setting https://raw.githubusercontent.com/hackclub/dinosaurs/main/ to https://raw.githubusercontent.com/hackclub/dinosaurs/main/folder_name. Either way, the site is down. I think moving it to a folder would be more convenient.

**Comment by TheGuyDangerous** [comment]
Should I work on the issue ? or is it available only to the community runners

**Comment by maxwofford** [comment]
We'll need to update [hack.af/draw-dino](https://hack.af/draw-dino), which is the big change to make. I'm totally fine with changing the repo structure, but this is where beginners make their first PR and I want to make sure that process is as smooth as possible for them.

**Comment by maxwofford** [comment]
Here's the repo link if anyone wants to take a crack at it https://github.com/hackclub/draw-dino

**Comment by BrightTheBackpack** [comment]
i can try when i  get home

**Comment by BrightTheBackpack** [comment]
If we decide to through with this, heres all the steps we would have to do
1. Move all the dino's into a folder
2. Edit draw-dino site
       -Change Public/steps/upload.mp4
       -Change line 228 from index.js to "Click into the drawings folder, then click "Add File"."
3. Change http://rawr.hackclub.com/ and https://geta.dino.icu/
       -Not 100% sure where the source code for these are

**Comment by sarthaktexas** [comment]
Un-assigning and closing because no work has been done. _[Geta.dino.icu](geta.dino.icu) was on repl.it deployments and I think we can forget about it for now until somebody rebuilds that._ Since [rawr.hackclub.com](rawr.hackclub.com) exists, I don't think there's a need to move the repository structure around. The workflow works, and is meant for beginners, and if this is an issue of not being able to get to the README easily, [rawr.hackclub.com](rawr.hackclub.com) fixes that.
