### ISSUE TITLE
Shouldn't be looking like this?

### ISSUE THREAD

**Issue by Jonak-Adipta-Kalita** [hackclub/dinosaurs#928]
![image](https://github.com/hackclub/dinosaurs/assets/70377522/1004036a-259e-4027-8861-b6ead4751e69)

Should be fixed by adding a space between
https://github.com/hackclub/dinosaurs/blob/main/README.md?plain=1#L3053 and
https://github.com/hackclub/dinosaurs/blob/main/README.md?plain=1#L3054

@wsdevv (pinging because those lines were added by you :))

**Comment by wsdevv** [comment]
Alright, on it sorry, didn't really check lol oops.

**Comment by wsdevv** [comment]
Submitted a PR.
